# Generated by Django 3.0.7 on 2020-06-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='good',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
